### ISSUE TITLE
Project page count issue bcoz of Search By Staff Role filter

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#737]
### Pending count is 6,
![2](https://user-images.githubusercontent.com/46882964/69539129-e12e0280-0fa9-11ea-9b2e-868fbfbdb6ad.png)
### But when i click on lead, project is not appeared. Because staff role filter is not change to executive.
![3](https://user-images.githubusercontent.com/46882964/69539245-1c303600-0faa-11ea-8647-1e76f480b915.png)

**Comment by mitulpanch** [comment]
Problem is :

by Default Project and Status both load as Executive
and Role filter is set to Project Manager

so second time click on any filter gives project as Manager,
that makes project count change.

**Comment by mitulpanch** [comment]
Roles are setting in Manager, Project Manager then Executive Order,

That is messing things as it takes time to load page.

so now setting manager then directly executive , not setting Project Manager role as it show lower number of project.

@vinpahilwani required that executive should be default role not **Project Manager**, because it show lower number of projects.

this things were working perfectly before, but due to home page click required new roles and preloading Role filter made this error
