### ISSUE TITLE
Delete Blocked Company to Ease Load

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#789]
AS minimum Billing is in effect, all company which are not paying will go to Block state after some time depending upon their Credit/Discount.

I suggest we should delete database for these companies to ease our load of migration on each new version release.

We can also say that we do not keep your personal data to encourage privacy concerns.

**Comment by mitulpanch** [comment]
![Annotation 2019-12-11 103600](https://user-images.githubusercontent.com/5259926/70989721-1ed60500-20ea-11ea-8a6f-1cb3f89e827a.jpg)

I suggest this kind of warning messages

**Comment by mitulpanch** [comment]
We are already sending Block State email to clients.

`Action Required

Hello $$NofityUserName$$,

You are receiving this email because you are a EasyCloudBooks customer.

Your company $$NofityUserCompany$$ has balance of $$NofityUserDue$$ due to be paid for $$NofityUserPaymentMonth$$.

To ensure that your services are not interrupted, please ask your billing administrator to pay previous due by following this link:
$$NofityUserBillLink$$

If you have already cleared previous month dues, please disregard this message.

If you have any questions please Call on 08460001275/76 OR Email us at support@easycloudbooks.com for any Query.

Take Care,
EasyCloudBooks`

**Comment by mitulpanch** [comment]
We need guideline to do this.

How much time we should give them to start again?

**Comment by mitulpanch** [comment]
![Annotation 2019-12-11 103600](https://user-images.githubusercontent.com/5259926/70990932-8d1bc700-20ec-11ea-8612-7f6f6a87eb1c.jpg)

-----------------------------------

this is email that user will receive upon pending deletion

**Comment by mitulpanch** [comment]
Give 45 days to recover - @vinpahilwani 

example - 
if Company is blocked of 1st December -
1. send email on payment due mail until 15th December.
2. send Deletion warning email on 16th December.
3. Delete DB on 15th January if not paid.

**Comment by risipatel** [comment]
Hello Rushi patel,

You are receiving this email because you are a customer of Easycloudbooks.

Your company Test Pvt Ltd was blocked on Tuesday, 17 December 2019.

Blocked company and the data stored in them can be recovered for a limited time before the company gets permanently deleted. If you’d like to keep your company and its data, then you need to recover your company before Thursday, 16 January 2020.

To recover your blocked company go to the following link : 
https://user.easycloudbooks.com/Billing?acid=319

If you have already restored your company, please disregard this message.

If you take no action by Thursday, 16 January 2020, you will be unable to recover your company.

If you have any questions please Call on 08460001275/76 OR Email us at support@easycloudbooks.com for any Query.

Take Care,
EasyCloudBooks

**Comment by mitulpanch** [comment]
Deleting Database after 15 waiting to pay-up + 30 Days Deletion Warning(4 Emails to Owners) + 5 Days Final System Analyzing + 1 Day + Start Deleting + Storage Delete + Databse Delete

Finally Deleted status to company

**Comment by vinpahilwani** [comment]
Yes perfect
